#BOARD ?=teensy:avr:teensy36:usb=serial,speed=168,opt=o1std,keys=en-us
BOARD=teensy:avr:teensy31:usb=serial,speed=96,opt=o1std,keys=en-us

PORT ?=/dev/ttyACM0
HOMEDIR =$(HOME)
BUILD_PATH ?=$(HOMEDIR)/Arduino/build/$(SKETCH)/_$(build_aDjOkT_core)/_$(build_aDjOkT_board)/_$(build_aDjOkT_arch)/_$(build_aDjOkT_mcu)
MFM_PATH ?=$(HOMEDIR)/Arduino/Arduino_Make
include $(MFM_PATH)/_Makefile.master
